export default {
  TOGGLEPLAY : 'PLAYER/TOGGLEPLAY',
  CHANGECURRENTSONG : 'PLAYER/CHANGECURRENTSONG',
  SETQUEUE : 'CONTROL/SETQUEUE',
  PLAYNEXT : 'CONTROL/PLAYNEXT',
  PLAYPREVIOUS : 'CONTROL/PLAYPREVIOUS',
  ADDTOQUEUE : 'CONTROL/ADDTOQUEUE',
  INSERTINTOQUEUE : 'CONTROL/INSERTINTOQUEUE',
  REMOVEFROMQUEUE : 'CONTROL/REMOVEFROMQUEUE',
  UPDATECURRENTTIME : 'PLAYER/UPDATECURRENTTIME',
  UPDATEVOLUME : 'PLAYER/UPDATEVOLUME',
}
